### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [ohmae/dms-explorer#14]
With the app being open source, would you consider publishing the `.apk` file heare at Github (best attach it to the corresponding tag in `releases/`) – so folks avoiding Playstore can get it? I could then also automatically pick and place it into my [F-Droid compatible repo](https://android.izzysoft.de/repo) for easier install/update :smile_cat:

**Comment by ohmae** [comment]
Thanks for the suggestion. I still do not know how to use GitHub yet, [is this OK?](https://github.com/ohmae/DmsExplorer/releases/tag/v0.7.1)

**Comment by IzzySoft** [comment]
Yes, definitely! Will take care for it this evening (and report back when done), thanks!

**Comment by IzzySoft** [comment]
Thanks again! Your app was just [added to my repo](https://apt.izzysoft.de/fdroid/index/apk/net.mm2d.dmsexplorer). Feel free to link there (next to the *Google Play* link in the `README.md`) so folks know they can use the repo to install your app, stay informed about updates and apply them easily, using the F-Droid client.

**Comment by ohmae** [comment]
Thanks. After the next release, I will also publish .apk on GitHub.

**Comment by IzzySoft** [comment]
Great! I'd say then we could consider this issue solved :smile_cat: So unless you need it as a reminder to set something up for the next release (or want to keep it open for another reason), it could be closed. Big :+1: for you!

**Comment by IzzySoft** [comment]
@ohmae just to let you know: [MastoArt for DmsExplorer](https://mastodon.technology/@mondstern/102190897174419893) :smiley:

In case you wonder: [Mondstern](https://mastodon.technology/@mondstern) runs a project and creates [MastoArt](https://mastodon.technology/tags/mastoart) for selected FOSS apps, a.o. to raise awareness. Hope you like it!

**Comment by mondstern** [comment]
Hi, i painted your dmsexplorer logo. nice that you were happy.
