### ISSUE TITLE
Want to use with LAN

### ISSUE THREAD

**Issue by tf0054** [ohmae/dms-explorer#42]
Hi, I love this app and guess the best app as the DLNA client because of its simpleness.

These days some kind of [Android TV box](https://wiki.ezvid.com/best-android-tv-boxes?utm_expid=.P5CuW7_wRZa8PTflI7SayQ.0&utm_referrer=https%3A%2F%2Fwww.google.com%2F) flourishes and they are usually has a Ethernet interface which is good for having a stable connection for watching videos.

I know DmsExplorer couldnt deal with the Ethernet even with the latest, but think it will be better and more attractive if it could. So many box users will appreciate if you would consider to respond to this!

**Comment by ohmae** [comment]
Hi, thanks for the suggestion.
I was planning to do it later, but I completely forgotten. :smile:

I fixed it. https://github.com/ohmae/DmsExplorer/commit/e3060a318e6aaf6d5794a67b9312a0242f60eb3d

I am testing this to release now.
If you have a development environment, Could you check whether it works without problems in your environment?

**Comment by tf0054** [comment]
Awesome!
Thank you so much for your swift fix. I will check tonight and will comment here.

**Comment by tf0054** [comment]
I confirmed the latest cc17951 of dev branch worked perfectly on my Android TV box (geekbox)!

Thank you so much.

**Comment by ohmae** [comment]
Thnak you for your report.
I released [Ver.0.7.27](https://github.com/ohmae/DmsExplorer/releases/tag/v0.7.27).
