### ISSUE TITLE
Fail to work with samsung AllShare

### ISSUE THREAD

**Issue by rozhuk-im** [ohmae/dms-explorer#46]
Does not work with samsung AllShare - cant find device.
If device description contain strings:
```
<sec:ProductCap>smi,DCM10,getMediaInfo.sec,getCaptionInfo.sec</sec:ProductCap>
<sec:X_ProductCap>smi,DCM10,getMediaInfo.sec,getCaptionInfo.sec</sec:X_ProductCap>
```
In tcpdump log I see that android request device description xml file and get if, than nothing happen.
If I remove that two string than all work as expected.

Since this my commit: https://github.com/rozhuk-im/ssdpd/commit/f8681b10a1094f0c17d75f0b5f1379ba631d2de5

Probably this is mmupnp  bug.

**Comment by ohmae** [comment]
Thank you for contacting.
I checked your commit, I noticed that your XML was in the wrong format.
Your XML is missing a namespace URL of `sec`.
If you want to add `sec:ProductCap` or `sec:X_ProductCap`, you should add namespace attribute to root tag, like`xmlns:sec="http://www.sec.co.kr/dlna"`.
Could you please try this first?

**Comment by rozhuk-im** [comment]
Thanks!
You are right.
I add that namespace attr and now works: https://github.com/rozhuk-im/ssdpd/commit/23672b9d237e3151b75730d744aeb4da5e9c3b2f

PS:
1. In https://github.com/ohmae/mmupnp/blob/70448072dd8efc93e9376faa0be41a137ce96ba6/lib/src/test/resources/device-with-url-base.xml you have `xmlns:av="urn:schemas-sony-com:av"` but never use this name space.
2. Only two apps was broken by this namespace attr missing: AnDLNA and DmsExplorer.
