### ISSUE TITLE
Mobile vertical photos not recognized

### ISSUE THREAD

**Issue by danistrigaro** [ohmae/dms-explorer#47]
Dear,
thank you for this very easy to use application.
I've found an issue when I try to visualize the mobile taken photos shared trough DLNA media server.
The app is not able to recognize if the photo is vertical.
It does not happen with other devices.
Could you try to fix it?
Thank you
Daniele

**Comment by ohmae** [comment]
Yes, this app can not use the EXIF info.
However, at present, this app has a structural problem, making it difficult to add functions.
I am currently planning to rebuild the architecture of this app.
After that, I would like to fix it.
Please wait patiently. 😸

**Comment by ohmae** [comment]
Sorry I do not anything for this issue for a long time.
I fixed it. https://github.com/ohmae/DmsExplorer/commit/4b1458aafdf32848a9e6af3ce1cc6cf9cdfb21c0

**Comment by ohmae** [comment]
Released at Ver.0.7.32
