### ISSUE TITLE
DMS Explorer v0.7.37 | application does not work when I have internet connection

### ISSUE THREAD

**Issue by Icramss** [ohmae/dms-explorer#58]
# Expected behavior

The application should be running / working and not problematic.

# Actual behavior

Application not working. It said I do not have an internet connection. Though the connection I have is 4G. I prove it in the recording. I play youtube can be normal.

# How to reproduce

- Download app on playstore
- Open the app and turn on your internet connection
- it will say you do not have an internet connection.

### Device: ONE PLUS 2 OxygenOS Version 3.6.1
Operating System:Android 6.0.1
App Version : 0.7.37

# Recording of the bug

https://youtu.be/YYKSMc_vPw0

**Comment by ohmae** [comment]
That is correct behavior as designed. Because this app is a DLNA player.
Local network connection (WiFi) is required to use DLNA. It does not work on 4G.
