### ISSUE TITLE
Back arrow returns to device list instead of previous folder

### ISSUE THREAD

**Issue by toolstack** [ohmae/dms-explorer#59]
In previous versions, selecting the back arrow at the top left  would take you up one level in the directory tree.

In the last couple of releases it takes you all the way back to the root level/device selection menu.

Using the Android back button still works as expected.

**Comment by ohmae** [comment]
Hmm... I thought it was labor to return from a deep hierarchy of directories, so I changed it.
https://developer.android.com/training/design-navigation/ancestral-temporal
However, I think that this behavior is not so good 😅

**Comment by toolstack** [comment]
Perhaps having a back button and a home button might make sense?  Or even three, one for home, one for the root of the current device and a third for the device list?

**Comment by ohmae** [comment]
I'm thinking about how to achieve better operability, :thinking:  so please wait for a while.

**Comment by ohmae** [comment]
Since I could not come up with a good idea, I decided to make back arrow(up button) work as back key again. https://github.com/ohmae/DmsExplorer/commit/24ca51efc28230fb6fffd142b4ba47f567fd88f8
