### ISSUE TITLE
DMSExplorer 0.7.37_can not use. App does not work

### ISSUE THREAD

**Issue by nissa-sabyan** [ohmae/dms-explorer#60]
### EXPECTED BEHAVIOR

When launching, the app can be used. He has to work

### ACTUAL BEHAVIOR

Application not working. It does not work. He says **There is no available network connection**

### HOW TO REPRODUCE

- download on playstore
- please launch the app
- It will be can not work
- it only said **There is no available network connection**

` XIAOMI REDMI NOTE 4 `
` SYSTEM ANDROID 6.0.1 `
` APP VERSION 0.7.37 `

**Comment by ohmae** [comment]
same as #58
close
