### ISSUE TITLE
DTCP-IP support

### ISSUE THREAD

**Issue by gusutabopb** [ohmae/dms-explorer#82]
The README says:

> If the DMR supports it, DTCP-IP content playback is also possible.

However, when trying to playback videos from a DTCP-IP protected device (Regza TV) I get the following toast:

```
This app does not support playback of DRM content.
```

**Comment by ohmae** [comment]
It means that it is possible to give playback instructions to the DMR. It is the DMR that plays it, not this app.

**Comment by gusutabopb** [comment]
@ohmae Thanks for clarifying. And thanks for making this open source!
